# Generated by Django 4.1.7 on 2023-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
