# Generated by Django 4.1.7 on 2023-04-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_skill_icon_remove_skill_languages_skill_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
