# Generated by Django 4.1.7 on 2023-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
