# Generated by Django 4.1.7 on 2023-04-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_detail',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='main.service'),
        ),
    ]
