# Generated by Django 4.1.7 on 2023-04-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_service_detail_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_demo'),
        ),
    ]
